peer:
  id: peer0.org1.medimidi.com
  networkId: medical-network
  listenAddress: 0.0.0.0:7051
  address: 0.0.0.0:7051
  addressAutoDetect: false
  
  keepalive:
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    server:
      interval: 7200s
      timeout: 20s

  gossip:
    bootstrap: 127.0.0.1:7051
    useLeaderElection: false
    orgLeader: true
    
  tls:
    enabled: true
    cert:
      file: /etc/hyperledger/fabric/tls/server.crt
    key:
      file: /etc/hyperledger/fabric/tls/server.key
    rootcert:
      file: /etc/hyperledger/fabric/tls/ca.crt

  mspConfigPath: /etc/hyperledger/fabric/msp
  localMspId: Org1MSP
  
  fileSystemPath: /var/hyperledger/production
  
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256

chaincode:
  peerAddress: 0.0.0.0:7052
  listenAddress: 0.0.0.0:7052
  system:
    cscc: enable
    lscc: enable  
    escc: enable
    vscc: enable
    qscc: enable
    _lifecycle: enable

vm:
  endpoint: unix:///var/run/docker.sock

ledger:
  state:
    stateDatabase: CouchDB
    couchDBConfig:
      couchDBAddress: couchdb0.org1:5984
      username: admin
      password: adminpw